using Random
using Statistics
using DataFrames
using CSV
using Plots

const NVECTORS = 200
const NACTIVE = 10
const VECLEN = 20
const MAXVAL = 10

function tanimoto_similarity(v1::Vector{Int}, v2::Vector{Int})::Float64
    @assert length(v1) == length(v2)

    common = 0
    sum1 = 0
    sum2 = 0

    @inbounds for i in eachindex(v1)
        a = v1[i]
        b = v2[i]

        common += min(a, b)
        sum1 += a
        sum2 += b
    end

    denom = sum1 + sum2 - common

    return denom == 0 ? 1.0 : common / denom
end

function element_similarity(a::Int, b::Int)::Float64
    if a == 0 && b == 0
        return 0.5
    end

    return min(a, b) / max(a, b)
end

function vector_similarity(a::Vector{Int}, b::Vector{Int})::Float64
    @assert length(a) == length(b)

    return mean(element_similarity(a[i], b[i]) for i in eachindex(a))
end

function perturb_vector(proto::Vector{Int}; delta::Int = 1)::Vector{Int}
    return [
        clamp(x + rand(-delta:delta), 0, MAXVAL)
        for x in proto
    ]
end

function vectors_to_dataframe(records, veclen::Int)::DataFrame
    df = DataFrame()

    # Identifier column first.
    df.Name = [r.name for r in records]

    # Feature columns F1, F2, ...
    for i in 1:veclen
        df[!, "F$(i)"] = [r.vec[i] for r in records]
    end

    return df
end

# Random.seed!(12345)

# Prototype vector.
prototype = rand(0:MAXVAL, VECLEN)

# Active vectors, generated by perturbing the prototype.
active_vectors = [
    perturb_vector(prototype, delta=1)
    for _ in 1:NACTIVE
]

# Inactive/random background vectors.
nrandom = NVECTORS - NACTIVE

inactive_vectors = [
    rand(0:MAXVAL, VECLEN)
    for _ in 1:nrandom
]

# Build named records.
records = []

for i in 1:NACTIVE
    push!(
        records,
        (
            name = "active$(i)",
            vec = active_vectors[i],
            label = "active",
        )
    )
end

for i in 1:nrandom
    push!(
        records,
        (
            name = "inactive$(i)",
            vec = inactive_vectors[i],
            label = "inactive",
        )
    )
end

# Shuffle so active vectors are randomly distributed.
shuffle!(records)

# Write shuffled synthetic vectors.
df = vectors_to_dataframe(records, VECLEN)
CSV.write("synthetic.csv", df)

println("Wrote $(nrow(df)) rows to synthetic.csv")

# Write prototype vector separately.
prototype_record = [
    (
        name = "prototype",
        vec = prototype,
        label = "prototype",
    )
]

prototype_df = vectors_to_dataframe(prototype_record, VECLEN)
CSV.write("prototype.csv", prototype_df)

println("Wrote prototype.csv")

# Similarity distribution among inactive/random vectors only.
inactive_only = [r.vec for r in records if r.label == "inactive"]

random_sims = Float64[]

for i in 1:length(inactive_only)-1
    for j in i+1:length(inactive_only)
        push!(random_sims, tanimoto_similarity(inactive_only[i], inactive_only[j]))
    end
end

println()
println("Number of inactive/inactive similarities: ", length(random_sims))
println("Mean inactive similarity: ", round(mean(random_sims), digits=4))
println("Median inactive similarity: ", round(median(random_sims), digits=4))
println("Min inactive similarity: ", round(minimum(random_sims), digits=4))
println("Max inactive similarity: ", round(maximum(random_sims), digits=4))

histogram(
    random_sims,
    bins=40,
    xlabel="Similarity",
    ylabel="Count",
    title="Distribution of pairwise similarities among inactive vectors",
    legend=false,
)

savefig("random_similarity_distribution.png")
println("Wrote random_similarity_distribution.png")

# Compare prototype to all shuffled vectors.
ranked = [
    (
        name = records[i].name,
        shuffled_index = i,
        label = records[i].label,
        similarity = tanimoto_similarity(prototype, records[i].vec),
        vec = records[i].vec,
    )
    for i in eachindex(records)
]

sort!(ranked, by = x -> x.similarity, rev=true)

ranking_df = DataFrame(
    Name = [r.name for r in ranked],
    ShuffledIndex = [r.shuffled_index for r in ranked],
    Class = [r.label for r in ranked],
    Similarity = [r.similarity for r in ranked],
)

ranking_df.Distance = 1.0 .- ranking_df.Similarity

CSV.write("prototype_similarity.csv", ranking_df)

println("Wrote prototype_similarity.csv")

println()
println("Prototype vector:")
println(prototype)

println()
println("Most similar vectors to prototype:")
for r in ranked[1:20]
    println(
        "name=", r.name,
        " index=", r.shuffled_index,
        " class=", r.label,
        " similarity=", round(r.similarity, digits=4),
        " vector=", r.vec,
    )
end
