load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_proto_library", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "jama",
    srcs = [
    ],
    hdrs = glob(["*.h"]),
    deps = [
        "//Foundational/tnt",
    ],
)
