load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_proto_library", "cc_library", "cc_test")

cc_library(
    name = "xmlparser",
    srcs = [
        "xmlParser.cpp",
    ],
    hdrs = [
        "xmlParser.h",
    ],
    visibility = ["//visibility:public"],
)
