name: "conf1" fragment { smi: "[1CH3]{{6,1,0.5}}C{{4.5,0.5,0.5}}C{{3,0.5,0}}[1CH3]{{1.5,0,0}}" n: 1 attachment { ext: "[CH3]{{7.5,1,1}}" btype: BOND_SINGLE } attachment { atom: 3 ext: "[CH3]{{0,0,0}}" btype: BOND_SINGLE } usmi: "[1CH3]CC[1CH3]" }
name: "conf2" fragment { smi: "[1CH3]{{16,6,2.5}}C{{14.5,5.5,2.5}}C{{13,5.5,2}}[1CH3]{{11.5,5,2}}" n: 1 attachment { ext: "[CH3]{{17.5,6,3}}" btype: BOND_SINGLE } attachment { atom: 3 ext: "[CH3]{{10,5,2}}" btype: BOND_SINGLE } usmi: "[1CH3]CC[1CH3]" }
name: "confh" fragment { smi: "[H]{{6,2,0.5}}[1CH2]{{6,1,0.5}}C{{4.5,0.5,0.5}}C{{3,0.5,0}}[1CH3]{{1.5,0,0}}" n: 1 attachment { atom: 1 ext: "[CH3]{{7.5,1,1}}" btype: BOND_SINGLE } attachment { atom: 4 ext: "[CH3]{{0,0,0}}" btype: BOND_SINGLE } attachment { atom: 1 ext: "[H]{{6,2,0.5}}" btype: BOND_SINGLE } usmi: "[H][1CH2]CC[1CH3]" }
