// Using queries generated by ring_extraction, replace rings in molecules.

#include <iostream>
#include <memory>
#include <optional>

#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
#include "google/protobuf/text_format.h"

#define RESIZABLE_ARRAY_IWQSORT_IMPLEMENTATION

#include "Foundational/cmdline/cmdline.h"
#include "Foundational/iwmisc/misc.h"
#include "Foundational/iwstring/iw_stl_hash_set.h"

#include "Molecule_Lib/aromatic.h"
#include "Molecule_Lib/atom_typing.h"
#include "Molecule_Lib/istream_and_type.h"
#include "Molecule_Lib/molecule.h"
#include "Molecule_Lib/smiles.h"
#include "Molecule_Lib/standardise.h"

#include "Molecule_Tools/mformula.h"

#include "Molecule_Tools/ring_replacement_lib.h"

namespace ring_replacement {

using std::cerr;
using mformula::MFormula;

int
ReplaceCore(RingReplacement& ring_replacement,
            Molecule& m,
            IWString_and_File_Descriptor& output) {
  return ring_replacement.Process(m, output);
}

int
ReplaceCore(RingReplacement& ring_replacement,
            data_source_and_type<Molecule>& input,
            IWString_and_File_Descriptor& output) {
  Molecule * m;
  while ((m = input.next_molecule()) != nullptr) {
    std::unique_ptr<Molecule> free_m(m);

    if (! ring_replacement.Preprocess(*m)) {
      continue;
    }

    if (! ReplaceCore(ring_replacement, *m, output)) {
      cerr << "Fatal error processing " << m->name() << '\n';
      return 0;
    }
  }

  return 1;
}

int
ReplaceCore(RingReplacement& ring_replacement,
            const char * fname,
            FileType input_type,
            IWString_and_File_Descriptor& output) {
  if (input_type == FILE_TYPE_INVALID) {
    input_type = discern_file_type_from_name(fname);
  }

  data_source_and_type<Molecule> input(input_type, fname);
  if (! input.ok()) {
    cerr << "Cannot open '" << fname << "'\n";
    return 0;
  }

  return ReplaceCore(ring_replacement, input, output);
}

void
DisplayDashXOptions(std::ostream& output) {
  output << " -X no_valence_warning             do NOT display warnings about invalid valences\n";
  output << " -X arom_loss_warning              display warnings about aromaticity losses\n";
  ::exit(0);
}

int
Main(int argc, char** argv) {
  Command_Line cl(argc, argv, "vE:A:i:g:lcY:N:R:P:s:q:uapn:D:I:wX:dB:3z:F:f:");
  if (cl.unrecognised_options_encountered()) {
    cerr << "unrecognised_options_encountered\n";
    Usage(1);
  }

  set_copy_name_in_molecule_copy_constructor(1);

  const int verbose = cl.option_count('v');

  if (! process_standard_aromaticity_options(cl, verbose, 'A')) {
    cerr << "Cannot process aromaticity options\n";
    return 1;
  }

  if (! process_elements(cl, verbose, 'E')) {
    cerr << "Cannot process standard elements options (-E)\n";
    return 1;
  }

  if (cl.option_present('X')) {
    const_IWSubstring x;
    for (int i = 0; cl.value('X', x, i); ++i) {
      if (x == "no_valence_warning") {
        ring_replacement::set_display_valence_error_messages(0);
        if (verbose) {
          cerr << "Will NOT display valence error messges\n";
        }
      } else if (x == "arom_loss_warning") {
        set_warn_loss_of_aromaticity(1);
        if (verbose) {
          cerr << "Will display loss of aromaticity warnings\n";
        }
      } else if (x == "help") {
        DisplayDashXOptions(cerr);
      } else {
        cerr << "Unrecognised -X qualifier '" << x << "'\n";
        DisplayDashXOptions(cerr);
      }
    }
  }

  RingReplacement ring_replacement;
  if (! ring_replacement.Initialise(cl)) {
    cerr << "Cannot initialise options\n";
    Usage(1);
  }

  FileType input_type = FILE_TYPE_INVALID;

  if (cl.option_present('i')) {
    if (!process_input_type(cl, input_type)) {
      cerr << "Cannot determine input type\n";
      return 1;
    }
  } else if (!all_files_recognised_by_suffix(cl)) {
    return 1;
  }

  if (cl.empty()) {
    cerr << "Insufficient arguments\n";
    Usage(1);
  }

  IWString_and_File_Descriptor output(1);
  for (const char* fname : cl) {
    if (! ReplaceCore(ring_replacement, fname, input_type, output)) {
      cerr << "Fatal error processing '" << fname << "'\n";
      return 1;
    }
  }

  output.flush();

  if (verbose) {
    lillymol::set_include_coordinates_with_smiles(1);

    ring_replacement.Report(cerr);
  }

  return 0;
}

}  // namespace ring_replacement

int
main(int argc, char** argv) {
  int rc = ring_replacement::Main(argc, argv);

  return rc;
}
