#!/usr/bin/env bash

# Copy nanobind extension modules, and any private shared-library dependencies
# generated by bazel, to a directory suitable for PYTHONPATH.
#
# Keep this separate from copy_shared_libraries.sh while nanobind is a pilot so
# pybind and nanobind extension modules are not accidentally mixed.

set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
repo_home=$(cd "${here}/.." && pwd)

if [[ $# -gt 0 ]] ; then
  destdir=$1
else
  destdir="${repo_home}/nanobind_lib"
fi

mkdir -p "${destdir}"

copy_if_newer() {
  local source=$1
  local libname
  libname=$(basename "${source}")

  if [[ ! -s "${destdir}/${libname}" || "${source}" -nt "${destdir}/${libname}" ]] ; then
    echo "Copying ${source}"
    cp -f "${source}" "${destdir}"
  fi
}

copy_required_glob() {
  local pattern=$1
  local found=0

  shopt -s nullglob
  for lib in ${pattern}; do
    found=1
    copy_if_newer "${lib}"
  done
  shopt -u nullglob

  if [[ ${found} -eq 0 ]] ; then
    echo "${pattern} not found" >&2
    return 1
  fi
}

copy_optional_glob() {
  local pattern=$1

  shopt -s nullglob
  for lib in ${pattern}; do
    copy_if_newer "${lib}"
  done
  shopt -u nullglob
}

cd "${here}"

copy_required_glob "bazel-bin/nanobind/*.so"

# Future nanobind modules may depend on private LillyMol shared libraries. Copy
# any that exist, but do not require every directory to produce shared objects.
copy_optional_glob "bazel-bin/Molecule_Lib/lib*.so"
copy_optional_glob "bazel-bin/Molecule_Tools/lib*.so"
copy_optional_glob "bazel-bin/Molecule_Tools_Bdb/lib*.so"
copy_optional_glob "bazel-bin/Utilities/GFP_Tools/lib*.so"
